M48
; DRILL file KiCad 10.0.5 date 2026-10-07T16:54:33
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-07T16:54:33+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X183.75Y-89.41
X183.75Y-95.19
T2
X123.0Y-62.0
X123.0Y-126.0
X186.5Y-62.5
X186.5Y-125.5
M30
