M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Mon Aug 17 01:54:10 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-17T01:54:10+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X183.75Y-89.41
X183.75Y-95.19
T2
X123.0Y-62.0
X123.0Y-126.0
X186.5Y-62.5
X186.5Y-125.5
M30
