M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Mon Aug 17 01:54:11 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-17T01:54:11+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X185.75Y-96.6
X185.75Y-102.38
T2
X111.5Y-61.5
X111.5Y-138.5
X188.5Y-61.5
X188.5Y-138.5
M30
